version: '3.3'

services:

  mysql:
    image: mysql:5.7
    container_name: prestashop-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: prestapass
    volumes:
      - mysql_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestauser
      DB_PASSWD: prestapass
      PS_DEV_MODE: "1"
      PS_INSTALL_AUTO: "0"
      PS_DOMAIN: "localhost:8080"
    volumes:
      - prestashop_data:/var/www/html

volumes:
  mysql_data:
  prestashop_data:
